name: BuildTest

on:
  push:
    branches: [ build-test ]
    paths: 
      - 'SiraUtil/**'
      - '.github/workflows/build-test.yml'
  pull_request:
    branches: [ build-test ]
    paths: 
      - 'SiraUtil/**'
      - '.github/workflows/build-test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101 
      - name: GetStrippedRefs
        env:
          FILES_URL: ${{ secrets.BSFILES_URL }}
        run: wget --no-check-certificate "$FILES_URL" -q -O bsfiles.zip
      - name: ExtractRefs
        run: unzip -q -n bsfiles.zip -d ./Refs
      - name: Build
        id: Build
        env:
          FrameworkPathOverride: /user/lib/mono/4.7.2-api
        run: dotnet build --configuration Release
      - name: Echo Filename
        run: echo "$BUILDTEXT ($ASSEMBLYNAME)"
        env:
          BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
          ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.Build.outputs.filename }}
          path: ./SiraUtil/bin/Release/zip
      - name: CopyPDB
        working-directory: 'SiraUtil/bin/Release'
        run: cp ${{ steps.Build.oututs.assemblyname }}.pdb
      - name: Upload Artifact with PDB
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.Build.outputs.filename }}_WithPDB
          path: ./SiraUtil/bin/Release
