name: Build SiraUtil

on:
  push:
    branches: [ master ]
    paths: 
      - 'SiraUtil/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ master ]
    paths:  
      - 'SiraUtil/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: GetStrippedRefs
      env:
        FILES_URL: ${{ secrets.BSFILES_URL }}
      run: (new-object System.Net.WebClient).DownloadFile('${{ secrets.BSFILES_URL }}', 'bsfiles.zip')
      shell: powershell
    - name: ExtractRefs
      run: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        function Unzip
        {
            param([string]$zipfile, [string]$outpath)

            [System.IO.Compression.ZipFile]::ExtractToDirectory($zipfile, $outpath)
        }
        Unzip "bsfiles.zip" "./Refs"    
      shell: powershell
    - name: Build
      id: Build
      run: dotnet build --configuration Release -f net472
    - name: Echo Filename
      run: echo "$BUILDTEXT ($ASSEMBLYNAME)"
      env:
        BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
        ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ./SiraUtil/bin/Release/Final
    - name: CopyPDB
      working-directory: ./SiraUtil/bin/Release
      run: copy ${{ steps.Build.outputs.assemblyname }}.pdb Final/Plugins/${{ steps.Build.outputs.assemblyname }}.pdb
    - name: Upload Artifact With PDB
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}_WithPDB
        path: ./SiraUtil/bin/Release/Final
